language: java
jdk:
  - openjdk8
install:
  - mvn package
  - cd demo
  - mvn install:install-file -Dfile=../target/codecov-maven-plugin-1.1-SNAPSHOT.jar -DgroupId=dev.alexengrig -DartifactId=codecov-maven-plugin -Dpackaging=maven-plugin -Dversion=1.1-SNAPSHOT
